# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_id', models.IntegerField()),
                ('env_name', models.CharField(max_length=20)),
                ('env_url', models.CharField(max_length=200)),
                ('env_ip', models.TextField(max_length=400)),
                ('env_db', models.TextField(max_length=400)),
                ('env_comment', models.TextField(max_length=400)),
                ('env_author', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('file_size', models.CharField(max_length=20)),
                ('file_path', models.CharField(max_length=100)),
                ('file_author', models.CharField(max_length=20)),
                ('file_upload_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
