# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdriver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_upload_time',
            field=models.CharField(max_length=40),
        ),
    ]
